[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = [ "ALL" ]
ignore = [ "ANN", "PLR2004", "PLR0912", "PLR0913", "TC001", "C901", "B008" ]

[tool.ruff.per-file-ignores]
"examples/*.py" = [ "INP001", "T201" ]